
UPDATE `admin_events` SET `event_name` = 'Official cricket team selection for 1st year' WHERE `admin_events`.`event_id` = 1;
UPDATE `admin_events` SET `event_desc` = 'Inter-college cricket event is being scheduled. So gyus wake up and register for the selection.' WHERE `admin_events`.`event_id` = 1;
UPDATE `admin_events` SET `event_name` = 'Official basketball team selection for 3st year B.E' WHERE `admin_events`.`event_id` = 2;
UPDATE `admin_events` SET `event_name` = 'Inter-college cricket event is being scheduled. So gyus wake up and register for the selection.' WHERE `admin_events`.`event_id` = 3;
UPDATE `admin_events` SET `event_name` = 'Chess inter-state competation, selection for 2nd year B.E' WHERE `admin_events`.`event_id` = 4;
UPDATE `admin_events` SET `event_desc` = 'Inter-State chess event is being scheduled. So gyus wake up and register for the selection.' WHERE `admin_events`.`event_id` = 4;
UPDATE `admin_events` SET `event_desc` = 'Chess tournament, chess live scores, realtime battle etc' WHERE `admin_events`.`event_id` = 3;
UPDATE `admin_events` SET `event_name` = 'Basketball Championship' WHERE `admin_events`.`event_id` = 5;
UPDATE `admin_events` SET `event_desc` = 'From NBA physical to PC ' WHERE `admin_events`.`event_id` = 5;
UPDATE `admin_events` SET `event_name` = 'Tennis Titans' WHERE `admin_events`.`event_id` = 6;
UPDATE `admin_events` SET `event_desc` = 'Tennis singles and Doubles. No registration fee.' WHERE `admin_events`.`event_id` = 6;

UPDATE `admin_events` SET `event_name` = 'International golf' WHERE `admin_events`.`event_id` = 7;
UPDATE `admin_events` SET `event_name` = 'International Golf' WHERE `admin_events`.`event_id` = 7;
UPDATE `admin_events` SET `event_desc` = 'Golf is a club-and-ball sport in which players use various clubs to hit balls into a series of holes on a course in as few strokes as possible' WHERE `admin_events`.`event_id` = 7;
UPDATE `admin_events` SET `event_name` = 'National Rollball' WHERE `admin_events`.`event_id` = 8;
UPDATE `admin_events` SET `event_desc` = 'Chance to obtain a streak. BMSCE teams looking for new players.' WHERE `admin_events`.`event_id` = 8;
UPDATE `admin_events` SET `event_name` = 'Inter College Volleyball' WHERE `admin_events`.`event_id` = 9;
UPDATE `admin_events` SET `event_name` = 'Badminton Training' WHERE `admin_events`.`event_id` = 10;
UPDATE `admin_events` SET `event_name` = 'Marathon March 2K21' WHERE `admin_events`.`event_id` = 11;
UPDATE `admin_events` SET `event_name` = 'Football Championship' WHERE `admin_events`.`event_id` = 12;
UPDATE `admin_events` SET `event_name` = 'Basketball League' WHERE `admin_events`.`event_id` = 13;
UPDATE `admin_events` SET `event_name` = 'Intra College Tennis Team Doubles' WHERE `admin_events`.`event_id` = 14;
UPDATE `admin_events` SET `event_name` = 'Golf' WHERE `admin_events`.`event_id` = 15;
UPDATE `admin_events` SET `event_name` = 'Rollball national' WHERE `admin_events`.`event_id` = 16;
UPDATE `admin_events` SET `event_name` = 'International Volleyball' WHERE `admin_events`.`event_id` = 17;
UPDATE `admin_events` SET `event_name` = 'National Badminton' WHERE `admin_events`.`event_id` = 18;
UPDATE `admin_events` SET `event_name` = 'National Marathon' WHERE `admin_events`.`event_id` = 19;
UPDATE `admin_events` SET `event_desc` = 'Great Energy Gels for Long-Distance Running ' WHERE `admin_events`.`event_id` = 19;
UPDATE `admin_events` SET `event_name` = 'Basketball tournament' WHERE `admin_events`.`event_id` = 21;
UPDATE `admin_events` SET `event_name` = 'National tennis' WHERE `admin_events`.`event_id` = 22;
UPDATE `admin_events` SET `event_name` = 'Golf gambit' WHERE `admin_events`.`event_id` = 23;
UPDATE `admin_events` SET `event_name` = 'Rollball' WHERE `admin_events`.`event_id` = 24;
UPDATE `admin_events` SET `event_name` = 'Volleyball Infinity' WHERE `admin_events`.`event_id` = 25;
UPDATE `admin_events` SET `event_desc` = 'PESU organized, dates are tentaive' WHERE `admin_events`.`event_id` = 9;
UPDATE `admin_events` SET `event_desc` = 'Training venue: Gopal Maidan. Bring your own racket' WHERE `admin_events`.`event_id` = 10;
UPDATE `admin_events` SET `event_desc` = 'NGO organized Marathon' WHERE `admin_events`.`event_id` = 11;
UPDATE `admin_events` SET `event_desc` = 'In collaboration with NSS' WHERE `admin_events`.`event_id` = 22;
UPDATE `admin_events` SET `event_desc` = 'RVCE organized competition. Refreshments will be given.' WHERE `admin_events`.`event_id` = 23;
UPDATE `admin_events` SET `event_desc` = 'In collaboration with MSRIT' WHERE `admin_events`.`event_id` = 24;
UPDATE `admin_events` SET `event_desc` = 'Intra college basenall tournament' WHERE `admin_events`.`event_id` = 2;
UPDATE `admin_events` SET `event_desc` = 'Intra college baseball tournament' WHERE `admin_events`.`event_id` = 2;
UPDATE `admin_events` SET `event_name` = 'Golf under 25' WHERE `admin_events`.`event_id` = 15;
UPDATE `admin_events` SET `event_name` = 'Golf Under 25' WHERE `admin_events`.`event_id` = 15;
UPDATE `admin_events` SET `event_desc` = 'Major goals in football can only be achieved as part of a motivated team' WHERE `admin_events`.`event_id` = 12;
UPDATE `admin_events` SET `event_desc` = 'Dates are tentative.' WHERE `admin_events`.`event_id` = 13;
UPDATE `admin_events` SET `event_desc` = 'Semi-finals re registration open now.' WHERE `admin_events`.`event_id` = 14;
UPDATE `admin_events` SET `event_desc` = 'Open to all, any number of teams allowed.' WHERE `admin_events`.`event_id` = 15;
UPDATE `admin_events` SET `event_desc` = 'BMSCE organized 12th Rollball competition.' WHERE `admin_events`.`event_id` = 16;
UPDATE `admin_events` SET `event_desc` = 'Elimination round will go till 7 pm' WHERE `admin_events`.`event_id` = 17;
UPDATE `admin_events` SET `event_desc` = 'All major schools and colleges are participating.' WHERE `admin_events`.`event_id` = 18;
UPDATE `admin_events` SET `event_desc` = 'Inspiring a football team isn\'t easy, but these coaches and players knew just what to say' WHERE `admin_events`.`event_id` = 20;
UPDATE `admin_events` SET `event_desc` = '25th Basketball, SP will be the honored cheif guest' WHERE `admin_events`.`event_id` = 21;
SELECT `event_desc` FROM `admin_events` WHERE `admin_events`.`event_id` = 21
UPDATE `admin_events` SET `event_desc` = '25th Basketball, SP will be the honored chief guest' WHERE `admin_events`.`event_id` = 21;
UPDATE `admin_events` SET `event_desc` = 'Event organized by BIT. Cash prizes worth 10,000' WHERE `admin_events`.`event_id` = 25;
